Add ceph version to ceph-client
openstack/charm-ceph-mon pull request #4
Opened 2021-08-19 09:27 UTC by xiywang

Add ceph version to ceph-client for prometheus-ceph-exporter to use.

Block prometheus-ceph-exporter when ceph version >= nautilus.

2021-08-19 13:10 UTC, auria requested changes
Please find some comments inline.

OTOH, this PR needs to be created via git-review so it gets tracked in Gerrit. Besides, unit tests will probably need an update.

2021-08-19 13:10 UTC, auria commented on hooks/ceph_hooks.py
> +os.sys.path.insert(1, os.path.join(sys.path[0], "../files/nagios"))
The UOS team uses this approach when they need to add the charmhelpers folder to the path. You may want to use the same for the `../files/nagios/` folder.

```
_path = os.path.dirname(os.path.realpath(__file__))
_hooks = os.path.abspath(os.path.join(_path, "../hooks"))

def _add_path(path):
    if path not in sys.path:
        sys.path.insert(1, path)

_add_path(_hooks)
```

2021-08-19 13:10 UTC, auria commented on hooks/ceph_hooks.py
> +                    data.update({"version": ceph.resolve_ceph_version(hookenv.config("source") or "distro")})
Why not add this attribute to all the `ceph-client` relations? For now, it seems that only the Ceph exporter would use it, but the application name can be any that the user may want.

2021-08-19 13:10 UTC, auria commented on hooks/ceph_hooks.py
> +            data.update({"version": ceph.resolve_ceph_version(hookenv.config("source") or "distro")})
Same as above.

2021-08-20 06:22 UTC, openstack-mirroring commented
Thank you for your contribution!

This GitHub repository is just a mirror of https://opendev.org/openstack/charm-ceph-mon, where development really happens. Pull requests proposed on GitHub are automatically closed.

If you are interested in pushing this code upstream, please note that OpenStack development uses Gerrit for change proposal and code review.

If you have never contributed to OpenStack before, please see:
https://docs.openstack.org/contributors/code-and-documentation/quick-start.html

Feel free to reach out to the First Contact SIG by sending an email to the openstack-discuss list with the tag '[First Contact]' in the subject line. To email the mailing list, you must first subscribe which can be done here:
http://lists.openstack.org/cgi-bin/mailman/listinfo/openstack-discuss

2021-08-20 06:22 UTC, closed without merging